version: "3.3"

services:

  gateway:
    build:
      context: .
    image: flight-booking
    env_file: docker-compose.env
    environment:
      SERVICES: gateway
      PORT: 3000
    depends_on:
      - nats
      - internal_api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"
    networks:
      - internal

  flights:
    build:
      context: .
    image: flight-booking
    env_file: docker-compose.env
    environment:
      SERVICES: flights
    depends_on:
      - influx
      - nats
    networks:
      - internal

  internal_api:
    build:
      context: ./internalApi
    image: internal_api
    environment:
      - PYTHONUNBUFFERED=1
      - INFLUX_HOST=influx
      - INFLUX_PORT=8086
      - INFLUX_USERNAME=admin
      - INFLUX_PASSWORD=admin
      - DATABASE_NAME=flight-bookings
      - MONGODB_URL=mongodb://admin:admin@mongo:27017/?authSource=admin
      - DEBUG=True
    depends_on:
      - influx
      - nats
      - mongo
    networks:
      - internal
    ports:
      - 99:5000

  influx:
    image: influxdb:1.8
    volumes:
      - "./persisted/influxdb-storage/:/var/lib/influx.db"
    ports:
      - 8086:8086
    networks:
      - internal

  mongo:
    image: mongo:latest
    volumes:
      - "./persisted/mongodb-storage/:/data/db"
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - internal
    
  grafana:
    ports:
      - 4200:3000
    image: grafana/grafana
    depends_on:
      - influx
    links:
      - influx
    volumes:
      - "./persisted/grafana-storage/:/var/lib/grafana"
    networks:
      - internal

  nats:
    image: nats:latest
    networks:
      - internal

  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

networks:
  internal:
