version: "3.3"

services:

  gateway:
    build:
      context: .
    image: flight-booking
    env_file: docker-compose.env
    environment:
      SERVICES: gateway
      PORT: 3000
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"
    networks:
      - internal

  flights:
    build:
      context: .
    image: flight-booking
    env_file: docker-compose.env
    environment:
      SERVICES: flights
    depends_on:
      - influx
      - nats
    networks:
      - internal

  internal_api:
    build:
      context: ./internalApi
    image: internal_api
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - influx
      - nats
    networks:
      - internal
    ports:
      - 99:5000

  influx:
    image: influxdb:1.8
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
    volumes:
      - influxdata:/var/lib/influx.db
    ports:
      - 8086:8086
    networks:
      - internal
    
  grafana:
    ports:
      - 4200:3000
    image: grafana/grafana
    depends_on:
      - influx
    links:
      - influx
    volumes:
      - influxdata:/var/lib/influx.db
    networks:
      - internal

  nats:
    image: nats:latest
    networks:
      - internal

  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

networks:
  internal:

volumes:
  influxdata:
