version: "3.3"

services:

  gateway:
    build:
      context: .
    image: flight-booking
    env_file: docker-compose.env
    container_name: gateway
    environment:
      SERVICES: gateway
      PORT: 3000
    depends_on:
      - nats
      - internal_api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"
    networks:
      - flightbookings

  flights:
    build:
      context: .
    image: flight-booking
    container_name: flights
    env_file: docker-compose.env
    environment:
      SERVICES: flights
    depends_on:
      - influx
      - nats
    networks:
      - flightbookings
      
  weather:
    build:
      context: .
    image: flight-booking
    container_name: weather
    env_file: docker-compose.env
    environment:
      - CSV_FILE=/var/lib/dataset/seattle-weather.csv
      - PUBLISH_TOPIC=services/weather
      - MOSQUITTO_URL=tcp://mosquitto:1883
    volumes:
      - "./dataset:/var/lib/dataset"
    depends_on:
      - gateway
    networks:
      - flightbookings

  internal_api:
    build:
      context: ./internalApi
    image: internal_api
    container_name: internal_api
    environment:
      - PYTHONUNBUFFERED=1
      - INFLUX_HOST=influx
      - INFLUX_PORT=8086
      - INFLUX_USERNAME=admin
      - INFLUX_PASSWORD=admin
      - DATABASE_NAME=flight-bookings
      - MONGODB_URL=mongodb+srv://swiftly:JG3XJaqKAqPPxp6F@cluster0.q5ejg.mongodb.net/flight-bookings?retryWrites=true&w=majority
      - MONGO_URL_LOCAL=mongodb://admin:admin@mongo:27017/?authSource=admin
      - DEBUG=True
    depends_on:
      - influx
      - nats
      - mongo
    networks:
      - flightbookings
    ports:
      - 99:5000

  influx:
    image: influxdb:1.8
    container_name: influx
    volumes:
      - "./persisted/influxdb-storage/:/var/lib/influx.db"
    ports:
      - 8086:8086
    networks:
      - flightbookings

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      # - "./persisted/mongodb-storage/:/data/db"
      - mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - flightbookings
    
  grafana:
    ports:
      - 4200:3000
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - influx
    links:
      - influx
    volumes:
      - "./persisted/grafana-storage/:/var/lib/grafana"
    networks:
      - flightbookings

  nats:
    image: nats:latest
    container_name: nats
    networks:
      - flightbookings

  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - flightbookings
  
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
        - "80:8080"
    volumes:
        - "./swagger-ui:/usr/share/nginx/html/doc"
    environment:
        API_URL: doc/openapi.yaml
    networks:
      - flightbookings

networks:
  flightbookings:
    external: true

volumes:
  mongodb:
