version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./conf:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
  ekuiper:
    image: lfedge/ekuiper:1.4-slim
    container_name: ekuiper
    ports:
      - "9081:9081"
      - "20498:20498"
    environment:
      - MQTT_SOURCE__DEFAULT__SERVER=tcp://mosquitto:1883
  ekuiper_manager:
    image: emqx/ekuiper-manager:1.4
    container_name: manager
    ports:
      - "9082:9082"
  nodejs:
    build: ./nodejs
    container_name: nodejs
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
