version: "3"
services:

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./conf:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    networks:
      - flightbookings

  ekuiper:
    image: lfedge/ekuiper:1.4-slim
    container_name: ekuiper
    depends_on:
      - mosquitto
    ports:
      - "9081:9081"
      - "20498:20498"
    environment:
      - MQTT_SOURCE__DEFAULT__SERVER=tcp://mosquitto:1883
    networks:
      - flightbookings

  ekuiper_manager:
    image: emqx/ekuiper-manager:1.4
    container_name: manager
    depends_on:
      - ekuiper
    ports:
      - "9082:9082"
    networks:
      - flightbookings
  notifications:
    build: ./Notifications
    container_name: notifications
    ports:
      - "9999:80"
      - "9998:443"
    networks:
      - flightbookings

  analytics:
    build: ./analytics
    container_name: analytics
    ports:
      - "9997:5000"
    depends_on:
      - notifications
      - mosquitto
    environment:
      - GRPC_URL=notifications:80
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_SUB_CHANNEL=services/alerts
      - MONGO_URL_LOCAL=mongodb://admin:admin@mongo:27017/?authSource=admin
      - PYTHONUNBUFFERED=1
    networks:
      - flightbookings

networks:
  flightbookings:
    external: true

volumes:
  mongodb: