# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alerts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61lerts.proto\x12\x06\x61lerts\"T\n\x05\x41lert\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x0f\n\x07payload\x18\x05 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t23\n\x06\x41lerts\x12)\n\x04Send\x12\r.alerts.Alert\x1a\x10.alerts.Response\"\x00\x42\x1b\xaa\x02\x18GrpcNotifications.Protosb\x06proto3')



_ALERT = DESCRIPTOR.message_types_by_name['Alert']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Alert = _reflection.GeneratedProtocolMessageType('Alert', (_message.Message,), {
  'DESCRIPTOR' : _ALERT,
  '__module__' : 'alerts_pb2'
  # @@protoc_insertion_point(class_scope:alerts.Alert)
  })
_sym_db.RegisterMessage(Alert)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'alerts_pb2'
  # @@protoc_insertion_point(class_scope:alerts.Response)
  })
_sym_db.RegisterMessage(Response)

_ALERTS = DESCRIPTOR.services_by_name['Alerts']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\030GrpcNotifications.Protos'
  _ALERT._serialized_start=24
  _ALERT._serialized_end=108
  _RESPONSE._serialized_start=110
  _RESPONSE._serialized_end=136
  _ALERTS._serialized_start=138
  _ALERTS._serialized_end=189
# @@protoc_insertion_point(module_scope)
