# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13notifications.proto\x12\rnotifications\"[\n\x0cNotification\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x0f\n\x07payload\x18\x05 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t2O\n\rNotifications\x12>\n\x04Send\x12\x1b.notifications.Notification\x1a\x17.notifications.Response\"\x00\x42#Z\rnotifications\xaa\x02\x11GrpcNotificationsb\x06proto3')



_NOTIFICATION = DESCRIPTOR.message_types_by_name['Notification']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Notification = _reflection.GeneratedProtocolMessageType('Notification', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATION,
  '__module__' : 'notifications_pb2'
  # @@protoc_insertion_point(class_scope:notifications.Notification)
  })
_sym_db.RegisterMessage(Notification)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'notifications_pb2'
  # @@protoc_insertion_point(class_scope:notifications.Response)
  })
_sym_db.RegisterMessage(Response)

_NOTIFICATIONS = DESCRIPTOR.services_by_name['Notifications']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\rnotifications\252\002\021GrpcNotifications'
  _NOTIFICATION._serialized_start=38
  _NOTIFICATION._serialized_end=129
  _RESPONSE._serialized_start=131
  _RESPONSE._serialized_end=157
  _NOTIFICATIONS._serialized_start=159
  _NOTIFICATIONS._serialized_end=238
# @@protoc_insertion_point(module_scope)
